### ISSUE TITLE
Can't install on matisse model.

### ISSUE THREAD

**Issue by highlander317** [matteo0026/OTA#1]
Tried several versions of the firmware and can not get it to install, had to revert back to stock. Can you post full instructions on how to install??

**Comment by matteo0026** [comment]
Hi, installation instructions are in the first post.
https://forum.xda-developers.com/t/rom-unofficial-matisse-millet-lineageos-16-0.4032901/

You have to install twrp before, which is here and instructions are mentioned in the first post:
https://forum.xda-developers.com/t/recovery-3-7-0_9-unified-matisse-millet-rubenslte-twrp-recovery.4019831/

**Comment by highlander317** [comment]
Just says 
OOPS! no mirrors found.

**Comment by matteo0026** [comment]
On xda there's written that there is a mirror. Look in telegram channel https://t.me/tab4los
LOS16 can be downloaded also from releases section here on github.

**Comment by highlander317** [comment]
Followed the instruction as per forum, now stuck in a boot loop, just sits on recovery. Can not get into download or recovery no matter what.

**Comment by matteo0026** [comment]
I don't understand. Is it in bootloop or is it in recovery? Which recovery? Stock or TWRP? Before flashing custom ROM, have you updated you tablet to latest lollipop release?

**Comment by highlander317** [comment]
Was running 5.1.1 before starting, installed twrp, rebooted, got set warranty bit :Recovery , when trying to get back into recovery, no buttons do anything. Reboots back to 5.1.1 lollipop

**Comment by matteo0026** [comment]
5.1.1 means you have matissevewifi, as known as SM-T533. So, all the ROMs you find on xda can't be installed on your device.

**Comment by highlander317** [comment]
But I'm trying to install your ones from telegram tab4los matisswifi

**Comment by matteo0026** [comment]
Just tell me. Which variant do you have?
Matissewifi, as known as SM-T530, is a variant that has support for my ROMs. Stock firmware has Android 5.0.2 as Lollipop version.
Matissevewifi, as known as SM-T533, isn't supported. Stock firmware has Android 5.1.1 as Lollipop version. Moreover, it has a snapdragon 410 instead of 400. 410 is 64 bit, 400 is 32 bit. They are different under the hood, even if they are the same from outside.

**Comment by highlander317** [comment]
Mine is a SM-T533, didn't notice the ve in the matissevewifi.
Sorry for your time
